### ISSUE TITLE
Exception: Label encoder found an unknown label.

### ISSUE THREAD

**Issue by skr3178** [agemagician/ProtTrans#103]
Notebook: "ProtBert-BFD-FineTuning-PyTorchLightning-Localization"

First I got error with "typeError: __init__() got an unexpected keyword argument 'gradient_checkpointing". 

After setting it to false and then switching to true
`        parser.add_argument(
            "--gradient_checkpointing",
(hash)             default=False,
            default=True, 
(hash)             skr edited
            type=bool,
            help="Enable or disable gradient checkpointing which use the cpu memory \
                with the gpu memory to store the model.",
        )
        return parser`.

On running code:

`trainer.fit(model)`

I get new error.: Exception: Label encoder found an unknown label.

 Name                | Type             | Params
---------------------------------------------------------
0 | metric_acc          | Accuracy         | 0     
1 | ProtBertBFD         | BertModel        | 419 M 
2 | classification_head | Sequential       | 40 K  
3 | _loss               | CrossEntropyLoss | 0     
Epoch 0: 1%
108/11179 [00:18<32:24, 5.69it/s, loss=2.271, v_num=4-32, train_loss=2.09]
['Cytoplasm-Nucleus']
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/tmp/ipykernel_16029/2717931281.py in <module>
      2 # 6 START TRAINING
      3 # ------------------------
----> 4 trainer.fit(model)

~/anaconda3/envs/env3.7/lib/python3.7/site-packages/pytorch_lightning/trainer/states.py in wrapped_fn(self, *args, **kwargs)
     46             if entering is not None:
     47                 self.state = entering
---> 48             result = fn(self, *args, **kwargs)
     49 
     50             # The INTERRUPTED state can be set inside the run function. To indicate that run was interrupted

~/anaconda3/envs/env3.7/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloader, val_dataloaders, datamodule)
   1062             self.accelerator_backend = DataParallelBackend(self)
   1063             self.accelerator_backend.setup(model)
-> 1064             results = self.accelerator_backend.train()
   1065             self.accelerator_backend.teardown()
   1066 

~/anaconda3/envs/env3.7/lib/python3.7/site-packages/pytorch_lightning/accelerators/dp_backend.py in train(self)
     95     def train(self):
     96         model = self.trainer.model
---> 97         results = self.trainer.run_pretrain_routine(model)
     98         return results
     99 

~/anaconda3/envs/env3.7/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in run_pretrain_routine(self, model)
   1237 
   1238         # CORE TRAINING LOOP
-> 1239         self.train()
   1240 
   1241     def _run_sanity_check(self, ref_model, model):

~/anaconda3/envs/env3.7/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py in train(self)
    392                 # RUN TNG EPOCH
    393                 # -----------------
--> 394                 self.run_training_epoch()
    395 
    396                 if self.max_steps and self.max_steps <= self.global_step:

~/anaconda3/envs/env3.7/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py in run_training_epoch(self)
    477         # run epoch
    478         for batch_idx, (batch, is_last_batch) in self.profiler.profile_iterable(
--> 479                 enumerate(_with_is_last(train_dataloader)), "get_train_batch"
    480         ):
    481             # stop epoch if we limited the number of training batches

~/anaconda3/envs/env3.7/lib/python3.7/site-packages/pytorch_lightning/profiler/profilers.py in profile_iterable(self, iterable, action_name)
     76             try:
     77                 self.start(action_name)
---> 78                 value = next(iterator)
     79                 self.stop(action_name)
     80                 yield value

~/anaconda3/envs/env3.7/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py in _with_is_last(iterable)
   1321     it = iter(iterable)
   1322     last = next(it)
-> 1323     for val in it:
   1324         # yield last and has next
   1325         yield last, False

~/anaconda3/envs/env3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    626                 # TODO(https://github.com/pytorch/pytorch/issues/76750)
    627                 self._reset()  # type: ignore[call-arg]
--> 628             data = self._next_data()
    629             self._num_yielded += 1
    630             if self._dataset_kind == _DatasetKind.Iterable and \

~/anaconda3/envs/env3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _next_data(self)
   1331             else:
   1332                 del self._task_info[idx]
-> 1333                 return self._process_data(data)
   1334 
   1335     def _try_put_index(self):

~/anaconda3/envs/env3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _process_data(self, data)
   1357         self._try_put_index()
   1358         if isinstance(data, ExceptionWrapper):
-> 1359             data.reraise()
   1360         return data
   1361 

~/anaconda3/envs/env3.7/lib/python3.7/site-packages/torch/_utils.py in reraise(self)
    541             # instantiate since we don't know how to
    542             raise RuntimeError(msg) from None
--> 543         raise exception
    544 
    545 

Exception: Caught Exception in DataLoader worker process 5.
Original Traceback (most recent call last):
  File "/tmp/ipykernel_16029/1817995213.py", line 182, in prepare_sample
    targets = {"labels": self.label_encoder.batch_encode(sample["label"])}
  File "/home/skr/anaconda3/envs/env3.7/lib/python3.7/site-packages/torchnlp/encoders/label_encoder.py", line 100, in batch_encode
    return torch.stack(super().batch_encode(iterator, *args, **kwargs), dim=dim)
  File "/home/skr/anaconda3/envs/env3.7/lib/python3.7/site-packages/torchnlp/encoders/encoder.py", line 42, in batch_encode
    return [self.encode(object_, *args, **kwargs) for object_ in iterator]
  File "/home/skr/anaconda3/envs/env3.7/lib/python3.7/site-packages/torchnlp/encoders/encoder.py", line 42, in <listcomp>
    return [self.encode(object_, *args, **kwargs) for object_ in iterator]
  File "/home/skr/anaconda3/envs/env3.7/lib/python3.7/site-packages/torchnlp/encoders/label_encoder.py", line 87, in encode
    return torch.tensor(self.token_to_index.get(label, self.unknown_index))
RuntimeError: Could not infer dtype of NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/skr/anaconda3/envs/env3.7/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/skr/anaconda3/envs/env3.7/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/tmp/ipykernel_16029/1817995213.py", line 186, in prepare_sample
    raise Exception("Label encoder found an unknown label.")
Exception: Label encoder found an unknown label.

Here is my `conda list`

```
# packages in environment at /home/skr/anaconda3/envs/env3.7:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   1.4.0                    pypi_0    pypi
aiohttp                   3.8.3            py37h5eee18b_0  
aiosignal                 1.3.1                    pypi_0    pypi
anyio                     3.5.0            py37h06a4308_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py37h7f8727e_0  
async-timeout             4.0.2            py37h06a4308_0  
asynctest                 0.13.0                     py_0  
attrs                     22.1.0           py37h06a4308_0  
babel                     2.11.0           py37h06a4308_0  
backcall                  0.2.0              pyhd3eb1b0_0  
beautifulsoup4            4.11.1           py37h06a4308_0  
blas                      1.0                         mkl  
bleach                    4.1.0              pyhd3eb1b0_0  
blinker                   1.4              py37h06a4308_0  
bottleneck                1.3.5            py37h7deecbd_0  
brotlipy                  0.7.0           py37h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.18.1               h7f8727e_0  
ca-certificates           2022.10.11           h06a4308_0  
cachetools                4.2.4                    pypi_0    pypi
certifi                   2022.12.7        py37h06a4308_0  
cffi                      1.15.1           py37h5eee18b_3  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4            py37h06a4308_0  
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     4.12.0           py37h89c1867_0    conda-forge
conda-package-handling    2.0.2            py37h06a4308_0  
conda-package-streaming   0.7.0            py37h06a4308_0  
cryptography              38.0.4           py37h9ce1e76_0  
cuda                      11.6.1                        0    nvidia
cuda-cccl                 11.6.55              hf6102b2_0    nvidia
cuda-command-line-tools   11.6.2                        0    nvidia
cuda-compiler             11.6.2                        0    nvidia
cuda-cudart               11.6.55              he381448_0    nvidia
cuda-cudart-dev           11.6.55              h42ad0f4_0    nvidia
cuda-cuobjdump            11.6.124             h2eeebcb_0    nvidia
cuda-cupti                11.6.124             h86345e5_0    nvidia
cuda-cuxxfilt             11.6.124             hecbf4f6_0    nvidia
cuda-driver-dev           11.6.55                       0    nvidia
cuda-gdb                  12.0.90                       0    nvidia
cuda-libraries            11.6.1                        0    nvidia
cuda-libraries-dev        11.6.1                        0    nvidia
cuda-memcheck             11.8.86                       0    nvidia
cuda-nsight               12.0.78                       0    nvidia
cuda-nsight-compute       12.0.0                        0    nvidia
cuda-nvcc                 11.6.124             hbba6d2d_0    nvidia
cuda-nvdisasm             12.0.76                       0    nvidia
cuda-nvml-dev             11.6.55              haa9ef22_0    nvidia
cuda-nvprof               12.0.90                       0    nvidia
cuda-nvprune              11.6.124             he22ec0a_0    nvidia
cuda-nvrtc                11.6.124             h020bade_0    nvidia
cuda-nvrtc-dev            11.6.124             h249d397_0    nvidia
cuda-nvtx                 11.6.124             h0630a44_0    nvidia
cuda-nvvp                 12.0.90                       0    nvidia
cuda-runtime              11.6.1                        0    nvidia
cuda-samples              11.6.101             h8efea70_0    nvidia
cuda-sanitizer-api        12.0.90                       0    nvidia
cuda-toolkit              11.6.1                        0    nvidia
cuda-tools                11.6.1                        0    nvidia
cuda-visual-tools         11.6.1                        0    nvidia
dataclasses               0.8                pyh6d0b6a4_7  
dbus                      1.13.18              hb2f20db_0  
debugpy                   1.5.1            py37h295c915_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
entrypoints               0.4              py37h06a4308_0  
expat                     2.4.9                h6a678d5_0  
ffmpeg                    4.2.2                h20bf706_0  
fftw                      3.3.9                h27cfd23_1  
filelock                  3.9.0            py37h06a4308_0  
flit-core                 3.6.0              pyhd3eb1b0_0  
fontconfig                2.14.1               h52c9d5c_1  
freetype                  2.12.1               h4a9f257_0  
frozenlist                1.3.3            py37h5eee18b_0  
fsspec                    2022.11.0          pyhd8ed1ab_0    conda-forge
future                    0.18.3                   pypi_0    pypi
gds-tools                 1.5.0.59                      0    nvidia
giflib                    5.2.1                h7b6447c_0  
glib                      2.69.1               he621ea3_2  
gmp                       6.2.1                h295c915_3  
gnutls                    3.6.15               he1e5248_0  
google-auth               1.35.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.51.1                   pypi_0    pypi
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
huggingface-hub           0.11.1                   pypi_0    pypi
huggingface_hub           0.11.1                     py_0    huggingface
icu                       58.2                 he6710b0_3  
idna                      3.4              py37h06a4308_0  
imageio                   2.24.0                   pypi_0    pypi
importlib-metadata        4.11.3           py37h06a4308_0  
importlib_metadata        4.11.3               hd3eb1b0_0  
importlib_resources       5.2.0              pyhd3eb1b0_1  
install                   1.3.5                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
ipykernel                 6.15.2           py37h06a4308_0  
ipython                   7.31.1           py37h06a4308_1  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.5              pyhd3eb1b0_1  
jedi                      0.18.1           py37h06a4308_1  
jinja2                    3.1.2            py37h06a4308_0  
joblib                    1.1.1            py37h06a4308_0  
jpeg                      9e                   h7f8727e_0  
json5                     0.9.6              pyhd3eb1b0_0  
jsonschema                4.16.0           py37h06a4308_0  
jupyter                   1.0.0            py37h06a4308_8  
jupyter_client            7.4.8            py37h06a4308_0  
jupyter_console           6.4.4            py37h06a4308_0  
jupyter_core              4.11.2           py37h06a4308_0  
jupyter_server            1.23.4           py37h06a4308_0  
jupyterlab                3.5.2            py37h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.16.5           py37h06a4308_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.2               hac12032_0  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libarchive                3.5.2                h5de8990_0  
libblas                   3.9.0            12_linux64_mkl    conda-forge
libcblas                  3.9.0            12_linux64_mkl    conda-forge
libclang                  10.0.1          default_hb85057a_2  
libcublas                 11.9.2.110           h5e84587_0    nvidia
libcublas-dev             11.9.2.110           h5c901ab_0    nvidia
libcufft                  10.7.1.112           hf425ae0_0    nvidia
libcufft-dev              10.7.1.112           ha5ce4c0_0    nvidia
libcufile                 1.5.0.59                      0    nvidia
libcufile-dev             1.5.0.59                      0    nvidia
libcurand                 10.3.1.50                     0    nvidia
libcurand-dev             10.3.1.50                     0    nvidia
libcurl                   7.86.0               h91b91d3_0  
libcusolver               11.3.4.124           h33c3c4e_0    nvidia
libcusparse               11.7.2.124           h7538f96_0    nvidia
libcusparse-dev           11.7.2.124           hbbe9722_0    nvidia
libdeflate                1.8                  h7f8727e_5  
libedit                   3.1.20221030         h5eee18b_0  
libev                     4.33                 h7f8727e_1  
libevent                  2.1.12               h8f2d780_0  
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            11.2.0               h00389a5_1  
libgfortran5              11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h7f8727e_2  
libidn2                   2.3.2                h7f8727e_0  
liblapack                 3.9.0            12_linux64_mkl    conda-forge
libllvm10                 10.0.1               hbcb73fb_5  
libmamba                  0.23.1               hd8a31e3_1    conda-forge
libmambapy                0.23.1           py37h1ee4b26_1    conda-forge
libnghttp2                1.46.0               hce63b2e_0  
libnpp                    11.6.3.124           hd2722f0_0    nvidia
libnpp-dev                11.6.3.124           h3c42840_0    nvidia
libnvjpeg                 11.6.2.124           hd473ad6_0    nvidia
libnvjpeg-dev             11.6.2.124           hb5906b9_0    nvidia
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.37               hbc83047_0  
libpq                     12.9                 h16c4e8d_3  
libprotobuf               3.20.1               h4ff587b_0  
libsodium                 1.0.18               h7b6447c_0  
libsolv                   0.7.22               he621ea3_0  
libssh2                   1.10.0               h8f2d780_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.5.0                hecacb30_0  
libunistring              0.9.10               h27cfd23_0  
libuuid                   1.41.5               h5eee18b_0  
libvpx                    1.7.0                h439df22_0  
libwebp                   1.2.4                h11a3e52_0  
libwebp-base              1.2.4                h5eee18b_0  
libxcb                    1.15                 h7f8727e_0  
libxkbcommon              1.0.1                hfa300c1_0  
libxml2                   2.9.14               h74e7548_0  
libxslt                   1.1.35               h4e12654_0  
lxml                      4.9.1            py37h1edc446_0  
lz4-c                     1.9.4                h6a678d5_0  
lzo                       2.10              h516909a_1000    conda-forge
mamba                     0.23.1           py37h6dacc13_1    conda-forge
markdown                  3.4.1            py37h06a4308_0  
markupsafe                2.1.1            py37h7f8727e_0  
matplotlib-inline         0.1.6            py37h06a4308_0  
mistune                   0.8.4           py37h14c3975_1001  
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py37h7f8727e_0  
mkl_fft                   1.3.1            py37hd3c417c_0  
mkl_random                1.2.2            py37h51133e4_0  
multidict                 6.0.4                    pypi_0    pypi
nb_conda                  2.2.1            py37h06a4308_1  
nb_conda_kernels          2.3.1            py37h06a4308_0  
nbclassic                 0.4.8            py37h06a4308_0  
nbclient                  0.5.13           py37h06a4308_0  
nbconvert                 6.5.4            py37h06a4308_0  
nbformat                  5.7.0            py37h06a4308_0  
ncurses                   6.3                  h5eee18b_3  
nest-asyncio              1.5.6            py37h06a4308_0  
nettle                    3.7.3                hbbd107a_1  
notebook                  6.5.2            py37h06a4308_0  
notebook-shim             0.2.2            py37h06a4308_0  
nsight-compute            2022.4.0.15                   0    nvidia
nspr                      4.33                 h295c915_0  
nss                       3.74                 h0370c37_0  
numexpr                   2.8.4            py37he184ba9_0  
numpy                     1.21.5           py37h6c91a56_3  
numpy-base                1.21.5           py37ha15fc14_3  
oauthlib                  3.2.2                    pypi_0    pypi
olefile                   0.46               pyhd3eb1b0_0  
openh264                  2.1.1                h4ff587b_0  
openssl                   1.1.1s               h7f8727e_0  
packaging                 22.0             py37h06a4308_0  
pandas                    1.3.5                    pypi_0    pypi
pandocfilters             1.5.0              pyhd3eb1b0_0  
parso                     0.8.3              pyhd3eb1b0_0  
pcre                      8.45                 h295c915_0  
pcre2                     10.37                he7ceb23_1  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.4.0                    pypi_0    pypi
pip                       22.3.1           py37h06a4308_0  
pkgutil-resolve-name      1.3.10           py37h06a4308_0  
ply                       3.11                     py37_0  
prometheus_client         0.14.1           py37h06a4308_0  
prompt-toolkit            3.0.36           py37h06a4308_0  
prompt_toolkit            3.0.36               hd3eb1b0_0  
protobuf                  3.19.6                   pypi_0    pypi
psutil                    5.9.0            py37h5eee18b_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                    pypi_0    pypi
pybind11-abi              4                    hd3eb1b0_0  
pycosat                   0.6.4            py37h5eee18b_0  
pycparser                 2.21               pyhd3eb1b0_0  
pygments                  2.11.2             pyhd3eb1b0_0  
pyjwt                     2.4.0            py37h06a4308_0  
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pyqt                      5.9.2            py37h05f1152_2  
pyqt5-sip                 12.11.0          py37h6a678d5_1  
pyrsistent                0.18.0           py37heee7806_0  
pysocks                   1.7.1                    py37_1  
python                    3.7.16               h7a1cb2a_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.16.2           py37h06a4308_0  
python_abi                3.7                     2_cp37m    conda-forge
pytorch                   1.13.1          py3.7_cuda11.6_cudnn8.3.2_0    pytorch
pytorch-cuda              11.6                 h867d48c_1    pytorch
pytorch-lightning         0.9.0                      py_0    conda-forge
pytorch-mutex             1.0                        cuda    pytorch
pytorch-nlp               0.5.0                    pypi_0    pypi
pytz                      2022.7           py37h06a4308_0  
pyyaml                    6.0              py37h5eee18b_1  
pyzmq                     23.2.0           py37h6a678d5_0  
qt                        5.9.7                h5867ecd_1  
qt-main                   5.15.2               h327a75a_7  
qt-webengine              5.15.9               hd2b0992_4  
qtconsole                 5.4.0            py37h06a4308_0  
qtpy                      2.2.0            py37h06a4308_0  
qtwebkit                  5.212                h4eab89a_4  
readline                  8.2                  h5eee18b_0  
regex                     2022.10.31               pypi_0    pypi
reproc                    14.2.4               h295c915_1  
reproc-cpp                14.2.4               h295c915_1  
requests                  2.28.1           py37h06a4308_0  
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
ruamel_yaml               0.15.100         py37h27cfd23_0  
sacremoses                master                     py_0    huggingface
scikit-learn              1.0.2            py37h51133e4_1  
scipy                     1.7.3            py37h6c91a56_2  
send2trash                1.8.0              pyhd3eb1b0_1  
seqeval                   1.2.2              pyhd3deb0d_0    conda-forge
setuptools                65.6.3           py37h06a4308_0  
sip                       4.19.8           py37hf484d3e_0  
six                       1.16.0             pyhd3eb1b0_1  
sniffio                   1.2.0            py37h06a4308_1  
soupsieve                 2.3.2.post1      py37h06a4308_0  
sqlite                    3.40.1               h5082296_0  
tensorboard               2.2.0                      py_0    conda-forge
tensorboard-data-server   0.6.1            py37h52d8a92_0  
tensorboard-plugin-wit    1.8.1            py37h06a4308_0  
terminado                 0.17.1           py37h06a4308_0  
test-tube                 0.7.5                    pypi_0    pypi
threadpoolctl             2.2.0              pyh0d69192_0  
tinycss2                  1.2.1            py37h06a4308_0  
tk                        8.6.12               h1ccaba5_0  
tokenizers                0.13.2                   pypi_0    pypi
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.1            py37h06a4308_0  
torchaudio                0.13.1               py37_cu116    pytorch
torchmetrics              0.2.0                    pypi_0    pypi
torchvision               0.14.1               py37_cu116    pytorch
tornado                   6.2              py37h5eee18b_0  
tqdm                      4.64.1           py37h06a4308_0  
traitlets                 5.7.1            py37h06a4308_0  
transformers              4.25.1                   pypi_0    pypi
typing-extensions         4.4.0            py37h06a4308_0  
typing_extensions         4.4.0            py37h06a4308_0  
urllib3                   1.26.14          py37h06a4308_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1                    py37_1  
websocket-client          0.58.0           py37h06a4308_4  
werkzeug                  2.2.2            py37h06a4308_0  
wheel                     0.37.1             pyhd3eb1b0_0  
widgetsnbextension        3.5.2            py37h06a4308_0  
x264                      1!157.20191217       h7b6447c_0  
xz                        5.2.10               h5eee18b_1  
yaml                      0.2.5                h7b6447c_0  
yaml-cpp                  0.6.3                he1b5a44_4    conda-forge
yarl                      1.8.2                    pypi_0    pypi
zeromq                    4.3.4                h2531618_0  
zipp                      3.11.0           py37h06a4308_0  
zlib                      1.2.13               h5eee18b_0  
zstandard                 0.18.0           py37h5eee18b_0  
zstd                      1.5.2                ha4553b6_0  
```

**Comment by mheinzinger** [comment]
Maybe check this one and see if that helps: https://www.kaggle.com/code/ratthachat/proteinbert-lightning-multitasks

**Comment by skr3178** [comment]
Thank you for sharing this. It seems to have some issues with dependencies when running on kaggle. I will spend some time on resolving this. If there is a quick workaround such as some setting change it would be great. 
Using original environment. 

![image](https://user-images.githubusercontent.com/79299617/213828993-2919f8c7-b569-4857-86f7-c00ac025a4f0.png)


![image](https://user-images.githubusercontent.com/79299617/213828872-b336a4cb-3187-410b-bad1-34fe84ffbd3c.png)
![image](https://user-images.githubusercontent.com/79299617/213828903-26c1e009-02ef-4a36-99ff-c72bccf4483c.png)
