### ISSUE TITLE
ZeroDivisionError when running prott5_embedder.py

### ISSUE THREAD

**Issue by wojciech-galan** [agemagician/ProtTrans#110]
I tried to extract emgeddings for a simple protein with your `prott5_embedder.py`, but I'm still reciving this error: 
```
python Embedding/prott5_embedder.py --input a.fasta --output a.h5
Using device: cpu
Loading: Rostlab/prot_t5_xl_half_uniref50-enc
########################################
Example sequence: id1
A
########################################
Total number of sequences: 1
Average sequence length: 1.0
Number of sequences >1000: 0
RuntimeError during embedding for id1 (L=1). Try lowering batch size. If single sequence processing does not work, you need more vRAM to process your protein.

############# STATS #############
Total number of embeddings: 0
Traceback (most recent call last):
  File "Embedding/prott5_embedder.py", line 184, in <module>
    main()
  File "Embedding/prott5_embedder.py", line 181, in main
    get_embeddings( seq_path, emb_path, model_dir, per_protein=per_protein )
  File "Embedding/prott5_embedder.py", line 140, in get_embeddings
    end-start, (end-start)/len(emb_dict), avg_length))
ZeroDivisionError: float division by zero
```
I went down from a full protein sequence to just one amino-acid, but with no avail. Final `a.fasta` content:
```
>id1
A
```
Am I doing something wrong?

**Comment by wojciech-galan** [comment]
The issue disappeared when I installed pytorch with GPU support...
