### ISSUE TITLE
Issue running PT5_LoRA_Finetuning_per_residue_reg.ipynb

### ISSUE THREAD

**Issue by abelavit** [agemagician/ProtTrans#145]
Hello,

I am trying to finetune the ProtT5 using the script PT5_LoRA_Finetuning_per_residue_reg.ipynb and the same example dataset. However, I am getting the following error during training at the line; tokenizer, model, history = train_per_residue(my_train, my_valid, num_labels=3, batch=1, accum=1, epochs=1, seed=42, gpu=1):

`
2024-03-18 12:10:53.005425: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-18 12:10:54.308832: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the legacy (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set legacy=False. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Detected kernel version 3.10.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

  0%|          | 0/9712 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/export/home/s5319023/pbs/FineTuneProtT5/check_original/Original_Finetune_T5_embeding.py", line 570, in <module>
    tokenizer, model, history = train_per_residue(my_train, my_valid, num_labels=3, batch=1, accum=1, epochs=1, seed=42, gpu=1)
  File "/export/home/s5319023/pbs/FineTuneProtT5/check_original/Original_Finetune_T5_embeding.py", line 563, in train_per_residue
    trainer.train()
  File "/export/home/s5319023/.conda/envs/Finetine_ProtT5_2/lib/python3.10/site-packages/transformers/trainer.py", line 1624, in train
    return inner_training_loop(
  File "/export/home/s5319023/.conda/envs/Finetine_ProtT5_2/lib/python3.10/site-packages/transformers/trainer.py", line 1961, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/export/home/s5319023/.conda/envs/Finetine_ProtT5_2/lib/python3.10/site-packages/transformers/trainer.py", line 2902, in training_step
    loss = self.compute_loss(model, inputs)
  File "/export/home/s5319023/.conda/envs/Finetine_ProtT5_2/lib/python3.10/site-packages/transformers/trainer.py", line 2925, in compute_loss
    outputs = model(**inputs)
  File "/export/home/s5319023/.conda/envs/Finetine_ProtT5_2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/export/home/s5319023/.conda/envs/Finetine_ProtT5_2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/export/home/s5319023/pbs/FineTuneProtT5/check_original/Original_Finetune_T5_embeding.py", line 302, in forward
    outputs = self.encoder(
  File "/export/home/s5319023/.conda/envs/Finetine_ProtT5_2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/export/home/s5319023/.conda/envs/Finetine_ProtT5_2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/export/home/s5319023/.conda/envs/Finetine_ProtT5_2/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 1115, in forward
    layer_outputs = layer_module(
  File "/export/home/s5319023/.conda/envs/Finetine_ProtT5_2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/export/home/s5319023/.conda/envs/Finetine_ProtT5_2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/export/home/s5319023/.conda/envs/Finetine_ProtT5_2/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 695, in forward
    self_attention_outputs = self.layer[0](
  File "/export/home/s5319023/.conda/envs/Finetine_ProtT5_2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/export/home/s5319023/.conda/envs/Finetine_ProtT5_2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/export/home/s5319023/.conda/envs/Finetine_ProtT5_2/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 602, in forward
    attention_output = self.SelfAttention(
  File "/export/home/s5319023/.conda/envs/Finetine_ProtT5_2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/export/home/s5319023/.conda/envs/Finetine_ProtT5_2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/export/home/s5319023/.conda/envs/Finetine_ProtT5_2/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 521, in forward
    query_states = shape(self.q(hidden_states))  # (batch_size, n_heads, seq_length, dim_per_head)
  File "/export/home/s5319023/.conda/envs/Finetine_ProtT5_2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/export/home/s5319023/.conda/envs/Finetine_ProtT5_2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/export/home/s5319023/pbs/FineTuneProtT5/check_original/Original_Finetune_T5_embeding.py", line 197, in forward
    return F.linear(input, weight, self.bias)
RuntimeError: expected mat1 and mat2 to have the same dtype, but got: c10::Half != float

  0%|          | 0/9712 [00:00<?, ?it/s]

`

Thanks for the assistance.

**Comment by RSchmirler** [comment]
Can you clarify what mixed precision settings you are trying to run? and if deepspeed is enabled ?

My first guess is that loading the model in full precision will fix the error (remove `torch_dtype=torch.float16` from the `T5EncoderModel.from_pretrained()` call)

**Comment by malzamel01** [comment]
When the training functions cell, chang load model to;

model, tokenizer = PT5_classification_model(num_labels=num_labels, half_precision=False)

then run the training cell, that seemed to work for me.

**Comment by abelavit** [comment]
Thank you so much for your assistance.
