### ISSUE TITLE
Question about run ProtTrans in multiproces mode

### ISSUE THREAD

**Issue by luskyqi1995** [agemagician/ProtTrans#36]
**Hi,I am a new one learning to use the** [**ProtTrans**](https://github.com/agemagician/ProtTrans)

**I follow the tutorial :**[**https://github.com/agemagician/ProtTrans/blob/master/Prediction/ProtBert-BFD-Predict-SS3.ipynb**](https://github.com/agemagician/ProtTrans/blob/master/Prediction/ProtBert-BFD-Predict-SS3.ipynb)

```python
In [1]: import transformers

In [2]: from transformers import AutoTokenizer, AutoModelForTokenClassification,
   ...:  TokenClassificationPipeline

In [3]:
   ...: pipeline = TokenClassificationPipeline(
   ...:     model=AutoModelForTokenClassification.from_pretrained("Rostlab/prot_
   ...: bert_bfd_ss3"),
   ...:     tokenizer=AutoTokenizer.from_pretrained("Rostlab/prot_bert_bfd_ss3",
   ...:  skip_special_tokens=True))

In [4]: pipeline('EKEKERK')
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Out[4]:
[{'word': 'EKEKERK',
  'score': 0.9565243124961853,
  'entity': 'C',
  'index': 1,
  'start': 0,
  'end': 7}]
```

And I want to run the code in multiprocess mode with numbers of cpu.

The code is here:

```python

In [5]:
   ...: def sim_ProtTrans(fasta_str):
   ...:     pipeline = TokenClassificationPipeline(
   ...:     model=AutoModelForTokenClassification.from_pretrained("Rostlab/prot_
   ...: bert_bfd_ss3"),
   ...:     tokenizer=AutoTokenizer.from_pretrained("Rostlab/prot_bert_bfd_ss3",
   ...:  skip_special_tokens=True))
   ...:     return pipeline(fasta_str)[0]
   ...:

In [6]: sim_ProtTrans('EKEKERK')

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Out[6]:
{'word': 'EKEKERK',
 'score': 0.9565243124961853,
 'entity': 'C',
 'index': 1,
 'start': 0,
 'end': 7}
     
In [5]: a = ['KWKWKW','KWKWKC','KWKWKL','KWKWKR','KWKWKA','KWAWKW','KWKWRW','KWLWKW']
In [9]: from multiprocessing import Pool

In [10]: import pandas as pd
     
In [11]: def mulit_ProtTrans(fasta_list,core):
    ...:     df = pd.DataFrame(columns=('entity', 'index', 'score','word'))
    ...:     pool = Pool(core)
    ...:     counter = 0
    ...:     for x in fasta_list:
    ...:         a = pool.apply_async(sim_ProtTrans, (x,)).get()
    ...:         print('this is a result',a[0])
    ...:         counter = counter + 1
    ...:         print('this is',counter)
    ...:     df.loc[counter]=[a[0]['entity'], a[0]['index'], a[0]['score'], a[0]['word'
    ...: ]]
    ...:     return df
     
```

The error is here

```python
In [12]: mulit_ProtTrans(a,5)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
```

And after I ctrl+C

```
^CProcess ForkPoolWorker-1:
Process ForkPoolWorker-3:
Process ForkPoolWorker-5:
Process ForkPoolWorker-4:
Process ForkPoolWorker-12:
Process ForkPoolWorker-15:
Process ForkPoolWorker-14:
Process ForkPoolWorker-2:
Process ForkPoolWorker-13:
Process ForkPoolWorker-10:
Process ForkPoolWorker-9:
Process ForkPoolWorker-6:
Traceback (most recent call last):
  File "/Program/miniconda3/envs/py3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Program/miniconda3/envs/py3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Program/miniconda3/envs/py3/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/Program/miniconda3/envs/py3/lib/python3.7/multiprocessing/queues.py", line 351, in get
    with self._rlock:
  File "/Program/miniconda3/envs/py3/lib/python3.7/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
```

and

```
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-12-c6a736eed396> in <module>
----> 1 mulit_ProtTrans(a,5)

<ipython-input-3-2ec6df9eba4f> in mulit_ProtTrans(fasta_list, core)
      4     counter = 0
      5     for x in fasta_list:
----> 6         a = pool.apply_async(sim_ProtTrans, (x,)).get()
      7         print('this is a result',a[0])
      8         counter = counter + 1

~/Program/miniconda3/envs/py3/lib/python3.7/multiprocessing/pool.py in get(self, timeout)
    649
    650     def get(self, timeout=None):
--> 651         self.wait(timeout)
    652         if not self.ready():
    653             raise TimeoutError

~/Program/miniconda3/envs/py3/lib/python3.7/multiprocessing/pool.py in wait(self, timeout)
    646
    647     def wait(self, timeout=None):
--> 648         self._event.wait(timeout)
    649
    650     def get(self, timeout=None):

~/Program/miniconda3/envs/py3/lib/python3.7/threading.py in wait(self, timeout)
    550             signaled = self._flag
    551             if not signaled:
--> 552                 signaled = self._cond.wait(timeout)
    553             return signaled
    554

~/Program/miniconda3/envs/py3/lib/python3.7/threading.py in wait(self, timeout)
    294         try:    # restore state no matter what (e.g., KeyboardInterrupt)
    295             if timeout is None:
--> 296                 waiter.acquire()
    297                 gotit = True
    298             else:

KeyboardInterrupt:
```

**So is there anyone who can tell me how to fix it?**

**Comment by agemagician** [comment]
Our models use the hugging-face library that performs inference using either PyTorch or TensorFlow.

Both PyTorch and TensorFlow use multi-core inference automatically when running it on the CPU, so you don't need to perform any kind of threading for inference.
You can monitor your CPU cores, and you will find all of them are almost fully utilized during inference.

All you need is to send a batch of sequences to the pipeline as written on the "ProtBert BFD Predict SS3" example.

**Comment by luskyqi1995** [comment]
Thanks for your reply.
I get it.


On Mar 31, 2021 18:21，Ahmed ***@***.***> wrote：


Our models use the hugging-face library that performs inference using either PyTorch or TensorFlow.
Both PyTorch and TensorFlow use multi-core inference automatically when running it on the CPU, so you don't need to perform any kind of threading for inference.
 You can monitor your CPU cores, and you will find all of them are almost fully utilized during inference.
All you need is to send a batch of sequences to the pipeline as written on the "ProtBert BFD Predict SS3" example.
